Repository metwork-framework/mfbus, pull requests merged in 2020-04, with the labels that each got.

#5 build: add rabbitmq@mfext as dependency and fix rabbitmq_wrapper
  .layerapi2_dependencies
  adm/rabbitmq_wrapper
Labels: Merge Now, Status: Revision Needed

#6 Run rabbitmq
  adm/rabbitmq_wrapper
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed

#7 Run rabbitmq
  adm/mfxxx.status.custom
  adm/mfxxx.stop.custom
  adm/rabbitmq_wrapper
  config/circus.ini.custom
  config/config.ini.custom
Labels: Merge Now, Status: Review Needed

#8 feat: add basic integration test on rabbitmq
  integration_tests/0010_test_rabbitmq/.layerapi2_dependencies
  integration_tests/0010_test_rabbitmq/output_expected
  integration_tests/0010_test_rabbitmq/receive.py
  integration_tests/0010_test_rabbitmq/send.py
  integration_tests/0010_test_rabbitmq/test.sh
Labels: Merge Now, Status: Review Needed

#9 build: add sleep (maybe we should remove the test)
  adm/mfxxx.status.custom
Labels: Merge Now, Status: Review Needed

#10 Run rabbitmq
  .drone.yml
  adm/mfxxx.start.custom
  adm/mfxxx.status.custom
Labels: Merge Now, Status: Review Needed

#11 build: tests
  .drone.yml
  adm/mfxxx.start.custom
  adm/mfxxx.status.custom
  adm/mfxxx.stop.custom
Labels: Merge Now, Status: Review Needed

#12 Run rabbitmq
  adm/mfxxx.stop.custom
Labels: Merge Now, Status: Revision Needed

#13 Run rabbitmq
  integration_tests/0010_test_rabbitmq/send.py
Labels: Merge Now, Status: Review Needed

#14 build: improve test
  integration_tests/0010_test_rabbitmq/send.py
Labels: Merge Now, Status: Review Needed

#16 build: remove env variables which became useless
  adm/rabbitmq_wrapper
  integration_tests/0010_test_rabbitmq/test.sh
Labels: Merge Now, Status: Review Needed

#17 Run rabbitmq
  adm/before_start_rabbitmq
  config/Makefile
  config/config.ini.custom
  config/enabled_plugins
  config/rabbitmq.conf
Labels: Merge Now, Status: Review Needed

#18 build: cosmetics
  adm/Makefile
  adm/before_signal
  adm/before_start_rabbitmq
  adm/check_rabbitmq_status.py
  adm/get_epmd_pid
  adm/mfxxx.status.custom
  adm/mfxxx.stop.custom
  adm/rabbitmq_wrapper
  config/circus.ini.custom
Labels: Status: Review Needed
